linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - typecheck
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 10

  revive:
    severity: warning

  staticcheck:
    checks: ["all"]

  gosec:
    severity: medium

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - gosec
        - gocritic
